language: php

php:
  - 7.0
  - 5.6
  - hhvm

before_script:
  - composer install --prefer-dist --dev
  - ant prepare

after_script:
  - vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml

